# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92dfff8eaa41783704fe5a6a3de0d2e5cc68f0f5d2a0f8a16f4400fced315bd5e7ef9170ad7bfe238f6afdd2001cd9f257c1e943456fafb75624d1c41f0c75d9

test:
  secret_key_base: 5e9fa9097b397d9c9678caf976194c2f6404eeed808c9fbbaca4dc28b5859c6776e21ccfc614d007c95896a6320277bb47dc1e97d685a25d178e7080434e2e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
